### PR TITLE
Add option to draw tree hull in same color as text

### PR DESCRIPTION
**Pull request by Grantapher**
Also changes the color to follow a gradient hue from red to green between 1 and 10+ choppers.

### CODE REVIEW

**Comment by Grantapher** [comment]
Added some code to center the text within the hull of the tree, rather than being at the bottom.

**Comment by Infinitay** [comment]
Sorry I've been busy these days and spending time working on a RuneLite plugin for the Hallowed Sepulchre minigame. I'll take a look at these changes soon but everything seems fine. 

On another note, coincidentally, on the Hallowed Sepulchre plugin I'm working on I was rendering text over entities. I wanted to center it and did so very primitively by taking their hull's and dividing the height. It's not perfect but it kind of does the job. However there are issues when an object's hull constant changes such as the thrown sword or even the statues in the minigame whose heights keep fluctuating. Anyways, what I'm trying to say is that maybe it'll be beneficial to suggest an addition to RL's existing API to return the central point of a hull such as you implemented so that we no longer have to render text on the _ground_ and have it properly implemented.

**Comment by Grantapher** [comment]
Feel free to rip the centroid code for now, but yes I was considering adding it to RL itself. Not sure if it would help much with thrown sword because its hull kinda goes wild but it does seem like it could be useful generally.

**Comment by Infinitay** [comment]
https://github.com/Infinitay/tree-count-plugin/assets/6964154/fe9fe23a-6d2a-4240-b164-aa5ceae52355

LGTM, thanks again for the changes. Sorry for the delay.

**Pull request merged**
